# permissions for end users to edit cronbeta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronbeta-editor-role
rules:
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - cronbeta
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - cronbeta/status
  verbs:
  - get
